### ISSUE TITLE
Doesn't Execute

### ISSUE THREAD

**Issue by kurdtkobane** [kd8bny/cumulus#20]
Hi,
I am on Ubuntu 18.04 with a gnome shell.

I've installed Cumulus with wget and dpkg line command.

But i have an issue, the app doesn't execute. 
Here's the error message:

/usr/bin/cumulus 
/usr/lib/python2.7/dist-packages/cumulus/__init__.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk # pylint: disable=E0611
Traceback (most recent call last):
  File "/usr/bin/cumulus", line 47, in <module>
    import cumulus
  File "/usr/lib/python2.7/dist-packages/cumulus/__init__.py", line 26, in <module>
    from cumulus import CumulusWindow
  File "/usr/lib/python2.7/dist-packages/cumulus/CumulusWindow.py", line 23, in <module>
    from gi.repository import Gtk, WebKit # pylint: disable=E0611
ImportError: cannot import name WebKit

**Comment by vadrian89** [comment]
Hello, 
Since no one gave a response, I'm going to barge in.    
Cumulus from this repository and that ppa aren't developed anymore, if you are interested, there is a Qt port currently developed by me further [here](https://github.com/vadrian89/cumulus-qt#news).    
It hasn't been updated in a while but I am working in my free time and has more features than this version and more to come in the next version(when I will have the time to update with some welcoming-info screens).

**Comment by kd8bny** [comment]
@kurdtkobane   @vadrian89 thanks for replying. This fell through my notifications. This repo is no longer in development and what Adrian has developed is a superior product which I also use :) Please checkout his work
